application: badgemator
version: 1
runtime: python
api_version: 1

handlers:
- url: /badge.js
  script: main.py
- url: /badge-raw.js
  static_files: badge.js
  upload: badge.js
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /api/.+
  script: main.py
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)
